### ISSUE TITLE
Fails with UTC offset without colon

### ISSUE THREAD

**Issue by lazamar** [rtfeldman/elm-iso8601-date-strings#13]
Fails to parse this valid date `2001-11-11T11:11:11+0000` because the UTC offset does not have a colon.

SSCCE: https://ellie-app.com/3p4fLfFWwD4a1

According to Wikipedia (and our php server :P) UTC offsets may or may not have the colon.
![screenshot_2018-09-19_13-57-58](https://user-images.githubusercontent.com/11493705/45754680-2f13e180-bc14-11e8-87af-a075a56018e0.png)

**Comment by ringvold** [comment]
As far as I can tell time zone offset can be given without colon or with just the hours. **+01**, **+0100** and **+01:00** are all valid time zone notations.
Just to add a source other than wikipedia, see under "Time Zone": https://www.cl.cam.ac.uk/~mgk25/iso-time.html

**Comment by rtfeldman** [comment]
Fixed by https://github.com/rtfeldman/elm-iso8601-date-strings/pull/20
