### ISSUE TITLE
Fails when seconds digits not included

### ISSUE THREAD

**Issue by danabrams** [rtfeldman/elm-iso8601-date-strings#23]
`Iso8601.toTime "05-30-2019T21:35"` results in ```Err [{ col = 17, problem = ExpectingSymbol ":", row = 1 }]```, even though it's a perfectly acceptable format.

This is particularly important because this is the string format that a browser-native `"datetime-local" input` returns.

**Comment by jamesrweb** [comment]
@danabrams I began working on this issue and saw that your input currently gives a similar but different error than before `Err [{ col = 3, problem = UnexpectedChar, row = 1 }]`.

**Comment by rtfeldman** [comment]
Fixed by https://github.com/rtfeldman/elm-iso8601-date-strings/pull/24

**Comment by rtfeldman** [comment]
Fix released in [1.1.4](https://package.elm-lang.org/packages/rtfeldman/elm-iso8601-date-strings/1.1.4/) thanks to @danabrams's [PR](https://github.com/rtfeldman/elm-iso8601-date-strings/pull/24)!
