### ISSUE TITLE
Unhelpful TODO output from decoder failure

### ISSUE THREAD

**Issue by Janiczek** [rtfeldman/elm-iso8601-date-strings#25]
We've hit this in our app:

https://ellie-app.com/66WPxcDYHDHa1

```elm
Json.Decode.decodeString Iso8601.decoder "\"2010-09-31T14:29:25.01235Z\""
--> Err (Failure "TODO deadEndsToString" <internals>)
```

That message originates in [`elm/parser`](https://github.com/elm/parser/blob/7506b07eaa93a93d13b508b948c016105b0953c8/src/Parser.elm#L169-L171), and the best way forwards would probably be for `elm/parser` to either implement it or stop exposing it, but right now it's probably on the users of `elm/parser` to [**not** use it](https://github.com/rtfeldman/elm-iso8601-date-strings/blob/master/src/Iso8601.elm#L24) and instead provide their own implementation.

**Comment by rtfeldman** [comment]
Fixed in [1.1.4](https://package.elm-lang.org/packages/rtfeldman/elm-iso8601-date-strings/1.1.4/) thanks to @jamesrweb's [PR](https://github.com/rtfeldman/elm-iso8601-date-strings/pull/27)!
